name: Bug Report
description: Report a bug or defect
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: Short description of the bug
      placeholder: e.g. Login button unresponsive on mobile
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happens
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How to trigger the bug
      placeholder: |
        1. Go to...
        2. Click on...
        3. Observe...
    validations:
      required: false

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Browser, OS, device, app version, etc.
    validations:
      required: false

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Recordings
      description: Attach any visual evidence
    validations:
      required: false

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - Critical
        - High
        - Medium
        - Low
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Logs/Error Messages
      description: Stack traces, console output, etc.
      render: shell
    validations:
      required: false
